<?php

/**
 * Implements hook_element_info_alter().
 */
function file_auto_up_element_info_alter(&$types) {
  if (isset($types['managed_file'])) {
    $types['managed_file']['#process'][] = 'file_auto_up_managed_file_process';
  }
}

function file_auto_up_managed_file_process($element, &$form_state, $form) {
  if (!empty($element['#file_auto_up'])) {
    $element['#attributes']['data'][] = 'file-auto-up';
    $element['#attached']['js'][] = array(
      'type' => 'setting',
      'data' => array('file_auto_up' => array($element['#id']))
    );
    if (empty($element['#file'])) {
      drupal_add_css('#' . $element['#id'] . '-upload-button{display:none;}', array('type' => 'inline'));
    }
    $element['#attached']['js'][] = drupal_get_path('module', 'file_auto_up') . '/file_auto_up.js';
  }
  return $element;
}

/**
 * 增加上传文件的选项
 * Implements hook_form_FORM_ID_alter().
 */
function file_auto_up_form_field_ui_field_edit_form_alter(&$form, &$form_state) {
  if (isset($form['#field']) && in_array($form['#field']['type'], array('file', 'image'))) {
    $additions = &$form['instance']['settings'];
    $settings = $form['#instance']['settings'];
    $additions['file_auto_up'] = array(
      '#title' => t('auto upload'),
      '#type' => 'checkbox',
      '#description' => t('Select files automatically after upload'),
      '#default_value' => $settings['file_auto_up']
    );
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function file_auto_up_field_widget_form_alter(&$element, &$form_state, $context) {
  $field = $context['field'];
  if (isset($field['type']) && in_array($field['type'], array('file', 'image'))) {
    $settings = $context['field']['settings'];
    if (!empty($settings['file_auto_up'])) {
      foreach ($element as $key => $value) {
        $element[$key]['#file_auto_up'] = TRUE;
      }
    }
  }
}
